dataset:
    root: /home/ens/AT74470/datasets/caltech-101_processed_latents
    num_classes: 101
    num_classes_from_data: True

model:
    model_str: flaxDiT_XL_2
    num_classes: 101
    target_use_null_class: True
    class_dropout_prob: 0.1
    use_auxiliary_v_head: False
    uses_classifier_free_guidance: True
    use_training_guidance: False
    guidance_scale_strategy: classifier_free

diffusion:
    diffusion_steps: 1000
    noise_schedule: linear
    learn_sigma: True
    predict_xstart: False
    rescale_learned_sigmas: False

training:
    log_per_step: 250
    checkpoint_per_epoch: 1000000

    num_epochs: 200
    max_train_steps: 30000
    batch_size: 32
    use_ema: False
    learning_rate: 0.0001
    warmup_epochs: 5

    adam_b2: 0.999
    ema_type: const
    ema_val: 0.9999

    sample_per_step: 5000
    fid_per_step: 0
    fid_schedule:
        - from_step: 0
          until_step: 20000
          every_steps: 5000
        - from_step: 20000
          every_steps: 2000
    metric_num_steps:
        - 250
        - 4
        - 2
        - 1
    preview_guidance_scales:
        - 1.0
        - 1.5
        - 4.0
    preview_num_steps:
        - 1
        - 2    
        - 4
        - 250
    grad_accum_steps: 1
    save_best_fid_only: True
    best_fid_checkpoint_dir: best_fid
    save_eval_checkpoint_per_fid: True
    eval_checkpoint_dir: latest_eval
    half_precision: False
    half_precision_dtype: float16

    seed: 42

fid:
    device_batch_size: 16
    sample_device_batch_size: 32
    sample_log_every: 1
    sample_first_device_only: False
    num_samples: 10000
    cache_ref: '/home/ens/AT74470/imeanflow/files/fid_stats/caltech-101-fid_stats.npz'
    num_images_to_log: 16

fd_dino:
    arch: vitb14
    model_name: ''
    cache_ref: '/home/ens/AT74470/imeanflow/files/fdd_stats/caltech-101-fd_dino-vitb14_stats.npz'

sampling:
    num_steps: 250
    method: p_sample
    half_precision: False
    half_precision_dtype: float16
    omega: 1.5
    cfg_scale: 1.5
    t_min: 0.0
    t_max: 1.0

logging:
    use_wandb: True
    wandb_name: 'CALTECH_DIT_plain'
    wandb_project: 'plain_dit_finetune'
    wandb_entity: 'yara-mohammadi-bahram-1-ecole-superieure-de-technologie'
    wandb_tags:
        - caltech101
        - finetune
        - plain-dit
    wandb_notes: 'Caltech-101 DiT fine-tuning with original DiT diffusion objective'

load_from: '/home/ens/AT74470/imeanflow/files/weights/DiT-XL-2-256x256.pt'
partial_load: True
